### ISSUE TITLE
Allow the package controller to create destination namesapces for Curated Package deployments

### ISSUE THREAD

**Issue by cryptk** [aws/eks-anywhere-packages#601]
**What would you like to be added**:
Curated Packages should be allowed to create their targetNamespace perhaps with an addition to the `packages.packages.eks.amazonaws.com` CRD for `spec.createNamespace` which will default to `false` and provide the exact current behavior, but could optionally be set to `true` to tell the package controller to create the `targetNamespace` before deploying the package.

If you wanted to be extra safe, the package controller could error out if `spec.createNamespace` was set to `true` and the namespace already exists, unless the namespace was created by the package controller, which could be tracked via an annotation on the namespace.

**Why is this needed**:
Currently to deploy a Curated Package, you must first create the namespace that the package will deploy into, then you must create the Package resource in the correct eksa-packages- namespace.  This becomes even more tedious when you are deploying a Curated Package onto a workload cluster which is managed by a management cluster as you must then perform the following dance:

- change kubectl context to the target workload cluster
- create the required kubernetes namespace
- change kubectl context to the management cluster that the workload cluster belongs to
- create the requred Package resource

When deploying Curated Packages via a management tool (such as terraform) this becomes even more annoying as you must pass multiple kubernetes providers around to create namespaces on one cluster while defining packages on another cluster.

**Comment by lewisdiamond** [comment]
We could add support for automatically creating namespaces but this would have to be enabled by the administrator on the controller configuration side first. The reason we don't automatically create the namespace is because the controller runs with admin privileges and this would allow users with no access to namespace creation to leverage the controller to create any namespace they want.

We would add a `packagebundlecontroller` setting that allows packages to create namespaces and if it's `true` and the package also has `createNamespace: true`, the controller would then create the namespace. This would most likely default to false but we can also add a flag at install for it to be true everywhere. Does that sound like a solution that would work for your use-case?

**Comment by lewisdiamond** [comment]
This is now available in the latest release. In order to have the controller automatically create a namespace, set `createNamespace` to `true` in the `packagebundlecontroller` for the cluster. See https://anywhere.eks.amazonaws.com/docs/reference/packagespec/packages/#packagebundlecontrollerspec
